import { CheckCircle2, CircleDot, ExternalLink, GitBranch, Loader2, ShieldCheck, TestTube2, XCircle } from 'lucide-react';
import { formatUpdatedAt } from '../lib/format';
import { useGithubWorkflow } from '../hooks/useGithubWorkflow';
import { useTestSummary } from '../hooks/useTestSummary';
import type { TestBucket } from '../types';

function TestRow({ label, bucket, icon: Icon }: { label: string; bucket: TestBucket; icon: typeof TestTube2 }) {
  const hasRun = bucket.total > 0;
  const passed = hasRun && bucket.failed === 0;
  return (
    <div className="flex items-center justify-between gap-4 rounded-2xl border border-white/[0.05] bg-white/[0.025] p-4">
      <div className="flex items-center gap-3">
        <div className="grid h-9 w-9 place-items-center rounded-xl bg-slate-900/70 text-sky-300"><Icon className="h-4 w-4" /></div>
        <div>
          <p className="text-sm font-medium text-slate-200">{label}</p>
          <p className="mt-0.5 text-xs text-slate-600">{hasRun ? `${bucket.passed} passed • ${bucket.failed} failed${bucket.skipped ? ` • ${bucket.skipped} skipped` : ''}` : 'Awaiting a Playwright run'}</p>
        </div>
      </div>
      <div className="text-right">
        <p className="text-lg font-semibold tabular-nums text-white">{hasRun ? `${bucket.passed}/${bucket.total}` : '—'}</p>
        {hasRun && (passed ? <CheckCircle2 className="ml-auto mt-1 h-4 w-4 text-emerald-300" /> : <XCircle className="ml-auto mt-1 h-4 w-4 text-rose-300" />)}
      </div>
    </div>
  );
}

export function AutomationPanel() {
  const summary = useTestSummary();
  const workflow = useGithubWorkflow();

  return (
    <section className="panel overflow-hidden" data-testid="automation-panel">
      <div className="flex flex-col gap-3 border-b border-white/[0.06] p-5 sm:flex-row sm:items-center sm:justify-between sm:p-6">
        <div>
          <p className="eyebrow">QA automation</p>
          <h3 className="mt-1 text-lg font-semibold text-white">Test & pipeline status</h3>
          <p className="mt-1 text-xs text-slate-500">Counts are generated by the custom Playwright reporter—never typed into the UI.</p>
        </div>
        {summary.generatedAt && <span className="text-xs text-slate-600">Generated {formatUpdatedAt(summary.generatedAt)}</span>}
      </div>
      <div className="grid gap-4 p-5 sm:p-6 lg:grid-cols-[1fr_.72fr]">
        <div className="space-y-2">
          <TestRow label="API tests" bucket={summary.api} icon={TestTube2} />
          <TestRow label="UI tests" bucket={summary.ui} icon={CircleDot} />
          <TestRow label="Negative tests" bucket={summary.negative} icon={ShieldCheck} />
        </div>
        <div className="rounded-2xl border border-white/[0.06] bg-slate-950/55 p-5">
          <div className="flex items-center justify-between gap-3">
            <div className="grid h-10 w-10 place-items-center rounded-xl bg-white/[0.04] text-slate-300"><GitBranch className="h-5 w-5" /></div>
            {workflow.loading ? (
              <Loader2 className="h-4 w-4 animate-spin text-sky-300" />
            ) : workflow.status === 'success' ? (
              <span className="rounded-full bg-emerald-400/10 px-3 py-1 text-xs font-semibold text-emerald-300">Passing</span>
            ) : workflow.status === 'failure' ? (
              <span className="rounded-full bg-rose-400/10 px-3 py-1 text-xs font-semibold text-rose-300">Failing</span>
            ) : workflow.status === 'in_progress' ? (
              <span className="rounded-full bg-sky-400/10 px-3 py-1 text-xs font-semibold text-sky-300">Running</span>
            ) : (
              <span className="rounded-full bg-white/[0.04] px-3 py-1 text-xs font-semibold text-slate-500">{workflow.configured ? 'Unavailable' : 'Configure repo'}</span>
            )}
          </div>
          <p className="mt-5 text-sm font-semibold text-white">GitHub Actions CI</p>
          <p className="mt-2 text-xs leading-5 text-slate-500">The latest public workflow state is fetched from GitHub at runtime. The pipeline runs type checking, build validation, API tests and UI tests.</p>
          {workflow.updatedAt && <p className="mt-4 text-xs text-slate-600">Last update {formatUpdatedAt(workflow.updatedAt)}</p>}
          {workflow.url && (
            <a href={workflow.url} target="_blank" rel="noreferrer" className="mt-5 inline-flex items-center gap-2 text-xs font-semibold text-sky-300 transition hover:text-sky-200">View workflow run <ExternalLink className="h-3.5 w-3.5" /></a>
          )}
        </div>
      </div>
    </section>
  );
}
